#!/usr/bin/bash
set -euxo pipefail
mkdir /out

DIGEST=$(bootc container compute-composefs-digest /target)

KVER=$(ls /target/usr/lib/modules)

KARGS="rw composefs=${DIGEST}"
! [ -e /target/etc/kernel/cmdline ] || KARGS="${KARGS} $(cat /target/etc/kernel/cmdline)"

ukify build \
  --linux "/target/usr/lib/modules/${KVER}/vmlinuz" \
  --initrd "/target/usr/lib/modules/${KVER}/initramfs.img" \
  --cmdline "${KARGS}" \
  --os-release "@/target/usr/lib/os-release" \
  --signtool sbsign \
  --secureboot-private-key /run/secrets/secureboot.key \
  --secureboot-certificate /run/secrets/secureboot.pem \
  --output "/out/${KVER}.efi"
