on:
  schedule:
  - cron: '17 23 * * *'
  workflow_dispatch:
permissions:
  packages: write
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: redhat-actions/podman-login@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - env:
        SIGSTORE_PRIVATE: ${{ secrets.SIGSTORE_PRIVATE }}
        SEAL_SIGSTORE_PRIVATE: ${{ secrets.SEAL_SIGSTORE_PRIVATE }}
        SECURE_BOOT_KEY: ${{ secrets.SECURE_BOOT_KEY }}
      run: |
        set -euxo pipefail
        ./setup.sh
        ./update.sh
